name:                birdism
version:             0.3.1
github:              "ecthiender/birdism"
license:             BSD3
author:              "Anon Ray"
maintainer:          "rayanon004@gmail.com"
copyright:           "2022 Anon Ray"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/ecthiender/birdism#readme>

dependencies:
- base >= 4.7 && < 5
# use text for string-like everything
- text
# for efficient representation in some cases
- bytestring
# for our monad stack
- mtl
# for hashmap (using it in results)
- hashable
- unordered-containers
# for database access
- postgresql-simple
# for making http requests to external APIs
- wreq
- http-client # for using the types
# for parsing and building JSON request/responses
- aeson
- aeson-casing
- lens
# well who doesn't have to deal with date/time
- time
# for our http webserver
- servant
- servant-server
- servant-docs
- http-types
- wai
- wai-middleware-static
- wai-extra
- wai-cors
- warp
# async concurrency
- async
- file-embed
- say
- retry
- directory

library:
  source-dirs: src

default-extensions:
- BangPatterns
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- DerivingVia
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- OverloadedStrings
- QuasiQuotes
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators

ghc-options:
- -O2
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

executables:
  birdism:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -Wall
    dependencies:
    - birdism

tests:
  birdism-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - birdism
